apiVersion: v1
kind: ConfigMap
metadata:
  name: easyshop-config
  namespace: easyshop
data:
  MONGODB_URI: "mongodb://mongodb-0.mongodb-service.easyshop.svc.cluster.local:27017/easyshop"
  REDIS_URI: "redis://easyshop-redis.easyshop.svc.cluster.local:6379"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "https://letsdeployportfolio.in/api" 
  NEXTAUTH_URL: "https://easyshop.letsdeployportfolio.com"  
  NEXTAUTH_SECRET: "2hQ9sHSYVY0Wet4GHjNdhYK6KR+2Vcis2jpcLFoDLqY="
  JWT_SECRET: "8ec834bb42eb8d03af7203e7500501fa6c2236e6f43d538701ec26f49e90b8d3"
