apiVersion: v1
kind: ConfigMap
metadata:
  name: easyshop-config
  namespace: easyshop
data:
  MONGODB_URI: "mongodb://mongodb-service:27017/easyshop"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "http://3.137.138.22/api"  # Replace with your YOUR_EC2_PUBLIC_IP
  NEXTAUTH_URL: "http://3.137.138.22"             # Replace with your YOUR_EC2_PUBLIC_IP
  NEXTAUTH_SECRET: "gk5m3dM2tkEqq1PxjKBe481zabi1zQGLIcZJMHXXYRc="
  JWT_SECRET: "572f1f6d0373d6af5f469269907549667cf6e2d8c9f6f6758dbca7340919c6ba"
