apiVersion: v1
kind: Secret
metadata:
  name: easyshop-secrets
  namespace: easyshop
type: Opaque
stringData:
  JWT_SECRET: "572f1f6d0373d6af5f469269907549667cf6e2d8c9f6f6758dbca7340919c6ba"
  NEXTAUTH_SECRET: "gk5m3dM2tkEqq1PxjKBe481zabi1zQGLIcZJMHXXYRc="
